### ISSUE TITLE
Negative Prompt is not taken into consideration

### ISSUE THREAD

**Issue by SergioGonzalez1996** [SirVeggie/extension-style-vars#4] opened 2024-12-03 05:05 UTC
Hello! Thanks for the extension!

I've been messing around with the it, especially with the Random feature, which I think it's the best since it gets whatever you have in the style.csv and don't have to mess with other files. 

However, I've noticed that it only changes the Positive Prompt, and leave the Negative as it is, even if the selected style have something on the negative. 

So, for example, if I have an style called "Waterfall" with positive: "waterfall, water, river" and Negative "wet, partially submerged", and call it with "$Waterfall" it will re-write the Positive Prompt, but the negative will be leave blank. 
Of course it was a silly example, but I've tested it with more complex prompts, will leave some pictures inside A11111

Style example:
![Style Editor](https://github.com/user-attachments/assets/831c2493-2da6-4689-ae16-ac418b964fdf)
After generation:
![After Generation](https://github.com/user-attachments/assets/d0ac1907-eb20-4b8d-8dcd-2b84dc482efa)

**Comment by SirVeggie** [comment] 2024-12-03 07:42
It is working as intended. You have to also add the $waterfall to the negative prompt, otherwise it wouldn't know at which spot it should insert the style text. It is mentioned in the readme.

**Comment by SergioGonzalez1996** [comment] 2024-12-04 08:32
**Oh. You are totally right... My bad, I'm sorry.** 

Well, I checked it, and it works as intended, but I have a question about the randomization function, if I may.

So, let's say I have 3 styles: $Waterfall, $City and $Forest.
To make it random, it would be {$Waterfall|$City|$Forest} in positive prompt, and again it works perfectly. 
But then, those 3 styles have something for negative prompt, so I added {$Waterfall |$City|$Forest} to the negative prompt... The extension will randomize the negative prompt again, so I end up with a mix of the styles between negative and positive prompt.
For example, the extension will select $Waterfall for positive and $City for negative.

Is there any way to force or synchronize it? So if it selects $Waterfall for positive, also select it for negative
I tested a few times and I don't know if I'm doing something wrong
Thanks in advance

**Comment by SirVeggie** [comment] 2024-12-04 09:12
You're right, what you're describing is a limitation and is not currently possible with the extension right now. I have actually had thoughts of a sync feature for the randomization, so I might add it later. I'll leave the issue open for that.

**Comment by SirVeggie** [comment] 2024-12-04 16:47
@SergioGonzalez1996 I have updated the extension to add the randomization linking feature. You can find the details in the readme. I did not test it, since I only use comfyui these days, but it should probably work. Go give it a test, and come back to close the issue or complain if it works for you or not!

**Comment by SergioGonzalez1996** [comment] 2024-12-05 05:36
Thanks for the quick update!
I updated the extension through the extension tab on A11111 and even checked the folder to make sure it was correctly updated.

First, I checked the **current** features of the extension, and everything works like it used to be: the vars, the randomization, everything works as intentad. 

However, the new update, the "group" or "sync" is not working. I followed the README instructions for the new sintaxis and tried it, with no success.  It was like the prompt wasn't edited, and the result looks like this:

![image](https://github.com/user-attachments/assets/eb69c96f-418e-48c7-af12-3b8709389411)
(forgive me for the low quality)

What I tried:

- Remove the $ from the Styles
- Changing the number _1_ for another 
- Leaving Negative Prompt blank
- Restarted A1111, and even disable my current theme
- I created an Style called "man", "woman", "suit", "dress" to replicate your example of {_1_|man|woman} wearing a {_1_|suit|dress} (check the image below, I also tried again but adding the $ before the styles, with no success)

![image](https://github.com/user-attachments/assets/1e100823-3fda-4837-81fa-dfa16b61a8d1)

Am I doing something wrong ?
P.S: Is ComfyUI good? I've been thinking of switching due to the better performance, but not sure

Edit: I forgot to check the console, when I opened it I noticed there were some errors, guess they will say more to you
![image](https://github.com/user-attachments/assets/1c5108d1-628c-4159-b6cb-59f44cc36df7)

**Comment by SirVeggie** [comment] 2024-12-06 14:18
Oh yeah, that error tells me all I need to know. I pushed a fix for it now.

ComfyUI is very good if you like tinkering with the generation process, and customizing it a lot. However, depending on your personality (me) you might end up spending more time tinkering than generating :D

It gives more creative freedom but comes at a cost of time and increased difficulty. The performance difference is mostly negligible, although that can also depend on your hardware.

**Comment by SergioGonzalez1996** [comment] 2024-12-07 06:01
Thanks for the update!

I've been playing with it and everything works as expected. 
I've been pushing it to the limits, with lot of styles, nested styles, different group numbers and doing stupid things to see what happens. So far no error, or malfunctions.

The only thing I noticed is that I trends to repeat an style, even if the Style pool is about 10 items, but I bet it's just my bad luck haha. Anyways, thanks again

And about the ComfyUI... I think I will pass hahaha I'm sure I will also spend lot of time just overthinking things

**Comment by SirVeggie** [comment] 2024-12-10 13:28
fantastic

**Closed as completed by SirVeggie** 2024-12-10 13:28 UTC
